// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameSalesmanRequest = "salesman_request"

// SalesmanRequest mapped from table <salesman_request>
type SalesmanRequest struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SalesmanID  int32     `gorm:"column:salesman_id;default:null" json:"salesmanIds"`
	Date        time.Time `gorm:"column:date;default:null" json:"accessDate"`
	Type        string    `gorm:"column:type;default:login" json:"type"`
	CreatedAt   time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
	RequestedID int64     `gorm:"column:requested_id;default:null" json:"employeeId"`
	IsApprove   int16     `gorm:"column:is_approve;default:null" json:"is_approve"`
	ApproveAt   time.Time `gorm:"column:approve_at;default:null" json:"approve_at"`
	ApproveID   int32     `gorm:"column:approve_id;default:null" json:"approve_id"`
	RequestAt   time.Time `gorm:"column:request_at;default:null" json:"request_at"`
	UserID 		int32 	  `gorm:"column:user_id;not null" json:"userId"`
}

// TableName SalesmanRequest's table name
func (*SalesmanRequest) TableName() string {
	return TableNameSalesmanRequest
}
