// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameCustomerAccess = "customer_access"

// CustomerAccess mapped from table <customer_access>
type CustomerAccess struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID  string    `gorm:"column:customer_id;not null" json:"customerIds"`
	AccessType  string    `gorm:"column:access_type;not null;default:DOUBLE CREDIT" json:"access_type"`
	DateStart   time.Time `gorm:"column:date_start;not null;default:CURRENT_DATE" json:"startDate"`
	DateEnd     time.Time `gorm:"column:date_end;not null;default:CURRENT_DATE" json:"endDate"`
	RequestAt   time.Time `gorm:"column:request_at;not null;default:now()" json:"request_at"`
	RequestedID int64     `gorm:"column:requested_id;not null" json:"employeeId"`
	IsApprove   int16     `gorm:"column:is_approve;default:null" json:"is_approve"`
	ApproveAt   time.Time `gorm:"column:approve_at;default:null" json:"approve_at"`
	ApproveID   int64     `gorm:"column:approve_id;default:null" json:"approve_id"`
	Note        string    `gorm:"column:note;default:null" json:"note"`
	Attachment  string    `gorm:"column:attachment;default:null" json:"attachment"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName CustomerAccess's table name
func (*CustomerAccess) TableName() string {
	return TableNameCustomerAccess
}
