// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameRuteMoveRequest = "rute_move_request"

// RuteMoveRequest mapped from table <rute_move_request>
type RuteMoveRequest struct {
	ID                    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RequestedID           int32     `gorm:"column:requested_id;not null" json:"employeeId"`
	RequestAt             time.Time `gorm:"column:request_at;not null;default:now()" json:"request_at"`
	RuteID                string    `gorm:"column:rute_id;not null" json:"ruteIds"`
	CustomerID            string    `gorm:"column:customer_id;default:null" json:"customer_id"`
	SalesmanIDDestination int32     `gorm:"column:salesman_id_destination;not null" json:"toSalesmanId"`
	DateEffective         time.Time `gorm:"column:date_effective;not null" json:"accessDate"`
	Note                  string    `gorm:"column:note;default:null" json:"note"`
	Attachment            string    `gorm:"column:attachment;default:null" json:"attachment"`
	IsApprove             int16     `gorm:"column:is_approve;default:null" json:"is_approve"`
	ApproveAt             time.Time `gorm:"column:approve_at;default:null" json:"approve_at"`
	ApproveID             int32     `gorm:"column:approve_id;default:null" json:"approve_id"`
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName RuteMoveRequest's table name
func (*RuteMoveRequest) TableName() string {
	return TableNameRuteMoveRequest
}
