// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameCustomerRelocation = "customer_relocation"

// CustomerRelocation mapped from table <customer_relocation>
type CustomerRelocation struct {
	ID                      int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	EmployeeID              int64     `gorm:"column:employee_id;not null" json:"employeeId"`
	CustomerID              string     `gorm:"column:customer_id;not null" json:"customerId"`
	RequestAt               time.Time `gorm:"column:request_at;not null;default:now()" json:"request_at"`
	LatitudeLongitudeBefore string    `gorm:"column:latitude_longitude_before;default:null" json:"latlongBefore"`
	LatitudeLongitudeAfter  string    `gorm:"column:latitude_longitude_after;default:null" json:"latlongAfter"`
	Note                    string    `gorm:"column:note;default:null" json:"note"`
	IsApprove               int16     `gorm:"column:is_approve;default:null" json:"is_approve"`
	ApproveAt               time.Time `gorm:"column:approve_at;default:null" json:"approve_at"`
	ApproveID               int64     `gorm:"column:approve_id;default:null" json:"approve_id"`
	CreatedAt               time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt               time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	UserID 		int32 	  `gorm:"column:user_id;not null" json:"userId"`
}

// TableName CustomerRelocation's table name
func (*CustomerRelocation) TableName() string {
	return TableNameCustomerRelocation
}
