// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameCustomerMoveRequestHiperion = "customer_move_request"

// CustomerMoveRequest mapped from table <customer_move_request>
type CustomerMoveRequestHiperion struct {
	ID                    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RequestedID           int64     `gorm:"column:requested_id;not null" json:"requestedId"`
	RequestAt             time.Time `gorm:"column:request_at;not null" json:"request_at"`
	SalesmanIDSource      string    `gorm:"column:salesman_id_source;default:null" json:"salesSource"`
	SalesmanIDDestination int32     `gorm:"column:salesman_id_destination;default:null" json:"salesTujuan"`
	CustomerID            string    `gorm:"column:customer_id;not null" json:"customerId"`
	DateEffective         time.Time `gorm:"column:date_effective;not null" json:"effectiveDate"`
	Attachment            string    `gorm:"column:attachment;default:null" json:"attachment"`
	Note                  string    `gorm:"column:note;default:null" json:"note"`
	Tag                   string    `gorm:"column:tag;not null" json:"tag"`
	IsApprove             int16     `gorm:"column:is_approve;default:null" json:"is_approve"`
	ApproveAt             time.Time `gorm:"column:approve_at;default:null" json:"approve_at"`
	ApproveID             int64     `gorm:"column:approve_id;default:null" json:"approve_id"`
	CreatedAt             time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt             time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName CustomerMoveRequest's table name
func (*CustomerMoveRequestHiperion) TableName() string {
	return TableNameCustomerMoveRequestHiperion
}
