// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameSalesmanAccess = "salesman_access"

// SalesmanAccess mapped from table <salesman_access>
type SalesmanAccess struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RequestAt         time.Time `gorm:"column:request_at;not null;default:now()" json:"request_at"`
	SalesmanID        string    `gorm:"column:salesman_id;not null" json:"salesmanIds"`
	AccessType        string    `gorm:"column:access_type;not null;default:CREDIT" json:"typeAccess"`
	DateStart         time.Time `gorm:"column:date_start;not null;default:now()" json:"startDate"`
	DateEnd           time.Time `gorm:"column:date_end;default:now()" json:"endDate"`
	RequestedID       int32     `gorm:"column:requested_id;not null" json:"employeeId"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	IsApprove         int16     `gorm:"column:is_approve;default:null" json:"is_approve"`
	ApproveAt         time.Time `gorm:"column:approve_at;default:null" json:"approve_at"`
	ApproveID         int32     `gorm:"column:approve_id;default:null" json:"approve_id"`
	Note              string    `gorm:"column:note;default:null" json:"note"`
	Attachment        string    `gorm:"column:attachment;default:null" json:"attachment"`
	ActiveType        string    `gorm:"column:active_type;not null;default:BUKA" json:"typeOpen"`
	IsKreditRetail    int16     `gorm:"column:is_kredit_retail;default:null" json:"isKreditRetail"`
	IsKreditSubGrosir int16     `gorm:"column:is_kredit_sub_grosir;default:null" json:"isKreditSubGrosir"`
	IsKreditGrosir    int16     `gorm:"column:is_kredit_grosir;default:null" json:"isKreditGrosir"`
	UserID 		int32 	  `gorm:"column:user_id;not null" json:"userId"`
}

// TableName SalesmanAccess's table name
func (*SalesmanAccess) TableName() string {
	return TableNameSalesmanAccess
}
