// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameSurveyProgramKompetitor = "survey_program_kompetitor"

// SurveyProgramKompetitor mapped from table <survey_program_kompetitor>
type SurveyProgramKompetitor struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID        int64     `gorm:"column:customer_id;default:null" json:"customer_id"`
	SalesmanID        int32     `gorm:"column:salesman_id;default:null" json:"salesman_id"`
	MerchandiserID    int32     `gorm:"column:merchandiser_id;default:null" json:"merchandiser_id"`
	TeamleaderID      int32     `gorm:"column:teamleader_id;default:null" json:"teamleader_id"`
	Datetime          time.Time `gorm:"column:datetime;default:null" json:"datetime"`
	ProgramName       string    `gorm:"column:program_name;default:null" json:"program_name"`
	Period            string    `gorm:"column:period;default:null" json:"period"`
	StartDate         time.Time `gorm:"column:start_date;default:null" json:"start_date"`
	EndDate           time.Time `gorm:"column:end_date;default:null" json:"end_date"`
	Information       string    `gorm:"column:information;default:null" json:"information"`
	CreatedAt         time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
	SyncKey           time.Time `gorm:"column:sync_key;default:now()" json:"sync_key"`
	Photo             string    `gorm:"column:photo;default:null" json:"photo"`
	LatitudeLongitude string    `gorm:"column:latitude_longitude;default:null" json:"latitude_longitude"`
	KompetitorID      int64     `gorm:"column:kompetitor_id;default:null" json:"kompetitor_id"`
}

// TableName SurveyProgramKompetitor's table name
func (*SurveyProgramKompetitor) TableName() string {
	return TableNameSurveyProgramKompetitor
}
