// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package structs

import (
	"time"
)

const TableNameValidateTransaksi = "validate_transaksi"

// ValidateTransaksi mapped from table <validate_transaksi>
type ValidateTransaksi struct {
	ID                string     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID        string     `gorm:"column:customer_id;default:null" json:"customer_id"`
	UserID            int32     `gorm:"column:user_id;default:null" json:"user_id"`
	UserLevelID       int32     `gorm:"column:user_level_id;default:null" json:"user_level_id"`
	SrID              int16     `gorm:"column:sr_id;default:null" json:"sr_id"`
	RayonID           int16     `gorm:"column:rayon_id;default:null" json:"rayon_id"`
	BranchID          int16     `gorm:"column:branch_id;default:null" json:"branch_id"`
	TransactionID     string     `gorm:"column:transaction_id;default:null" json:"transaction_id"`
	TransactionType   string    `gorm:"column:transaction_type;default:null" json:"transaction_type"`
	Datetime          time.Time `gorm:"column:datetime;default:null" json:"datetime"`
	IsValid           int16     `gorm:"column:is_valid;default:null" json:"is_valid"`
	Note              string    `gorm:"column:note;default:null" json:"note"`
	LatitudeLongitude string    `gorm:"column:latitude_longitude;default:null" json:"latitude_longitude"`
	CreatedAt         time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:now()" json:"updated_at"`
}

// TableName ValidateTransaksi's table name
func (*ValidateTransaksi) TableName() string {
	return TableNameValidateTransaksi
}
